version: '3.8'

services:
  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9000:9000" 
      - "9001:9001"  
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    restart: unless-stopped

 
  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    ports:
      - "6333:6333"  
      - "6334:6334" 
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped


  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped


  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env  
    depends_on:
      - minio
      - qdrant
      - ollama

volumes:
  minio_data:
  qdrant_data:
  ollama_data: